# The comment after each value is the value recommended by the developers.

[body]
average_vision_distance = 100.0 # 100.0
average_energy = 1500.0 # 1500.0
average_division_threshold = 2300.0 # 2300.0
skills_change_chance = 0.07 # 0.07

[energy]
energy_spent_const_for_mass = 0.0001 # 0.0001
energy_spent_const_for_skills = 0.0008 # 0.0008
energy_spent_const_for_vision_distance = 0.00005 # 0.00001
energy_spent_const_for_movement = 0.0004 # 0.0002
const_for_lifespan = 0.000005 # 0.000005

[viruses]
speedvirus_first_generation_infection_chance = 0.12 # 0.12
speedvirus_speed_decrease = 0.7 # 0.7
speedvirus_energy_spent_for_healing = 0.08 # 0.08
speedvirus_heal_energy = 280.0 # 280.0

visionvirus_first_generation_infection_chance = 0.1 # 0.1
visionvirus_vision_distance_decrease = 0.7 # 0.7
visionvirus_energy_spent_for_healing = 0.08 # 0.08
visionvirus_heal_energy = 280.5 # 280.5
